spring:
  config:
    activate:
      on-profile: config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seolyu?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 20
      pool-name: HIKARICP
      register-mbeans: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jackson:
    time-zone: GMT
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  jpa:
    hibernate:
      # 필드명 그대로 사용하기 위한 목적
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sql:
    # data.sql 같은 문서 자동 업로드 되는 걸 방지
    init:
      mode: never
  web:
    # addResourceHandlers 에서 다른 URL 맵핑되는 걸 방지
    resources:
      add-mappings: false
  mvc:
    # swagger 버전 문제
    pathmatch:
      matching-strategy: ant_path_matcher
    dispatch-options-request: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: wlsdiqkdrk@gmail.com
    password: bmfayahnijnivxbu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    redis:
      host: localhost

security:
  aes-key: ___seolyu_coor___

session:
  cookie:
    domain: .seolyu.com
    name: seyu


