name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Clean build test with Gradle
        run: ./gradlew clean bootJar -Pprofile=prd
        shell: bash
        
      - name: Make zip file 
        run: zip -r ./seolyu.zip .
        shell: bash
      
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3 
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./seolyu.zip s3://${{ secrets.AWS_S3_BUCKET }}/seolyu.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name ${{ secrets.AWS_CODEDEPLOY_NAME }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ secrets.AWS_CODEDEPLOY_GROUP }} --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=seolyu.zip
